# Site settings
title: Monkey2 news and info
email: blitzmunter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the monkey2 development blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.monkey-x.com" # the base hostname & protocol for your site
twitter_username: blitzmunter
github_username:  blitz-research

# Build settings
markdown: kramdown
